### ISSUE TITLE
TrueNAS Scale compatibility?

### ISSUE THREAD

**Issue by ishioni** [hpe-storage/truenas-csp#21]
Does this driver work with SCALE as well as CORE?

**Comment by datamattsson** [comment]
I kicked the tires on TrueNAS SCALE. The lights come on if you remove the "hardware_handler" row from the TrueNAS stanza in /etc/multipath.conf. I've [raised a PR to have this removed](https://github.com/hpe-storage/common-host-libs/pull/166) from the stanza. I've elaborated a bit more in the PR.

If the PR gets merged I'll perform some more testing in the next release. It will most likely be towards the end of the year.

**Comment by ishioni** [comment]
Looks the changes were merged. Good to go now?

**Comment by datamattsson** [comment]
@ishioni unfortunately not. We need to wait for a new build to get published. There's an imminent beta drop happening and a production released scheduled for early next year. I might start testing with the beta builds. If you're eager to get started, you can easily change the multipath.conf file manually on your worker nodes when the CSI driver has been deployed.

**Comment by ishioni** [comment]
Nah, that's ok, I'll wait :) I'll give this a spin once i get my new k3os based cluster up anyway

On a completely separate note, would you mind if I submitted a PR integrating the creation of the api secret and Storageclasses as part of values.yaml in the chart? I'm guessing you had a reason not shipping that in the first place?

**Comment by datamattsson** [comment]
The problem with `StorageClass` objects is that they're immutable from Helm (or at least was, when we started working on this). We had functionality to provide `StorageClass` and backend `Secrets` in the chart at launch but it caused more angst than it was worth in the end, hence we added those steps as post-install steps.

Also, k3os is not something we know if the CSI driver works with yet. Let me explore that.

**Comment by ishioni** [comment]
Please ignore the k3os part. I've abandoned it in lieu of a k3s+ubuntu setup. Waiting for a version which supports scale, and i'll be happy :)

**Comment by datamattsson** [comment]
Please give [v2.1.0](https://github.com/hpe-storage/truenas-csp/releases/tag/v2.1.0) a whirl and create a new issue if TrueNAS SCALE doesn't work out for you. TrueNAS SCALE 22.02 RC1 passes full CSI e2e tests in my lab with this release of the CSP.

As a side note. I've [verified the HPE CSI Driver for Kubernetes works with K3s](https://twitter.com/datamattsson/status/1484334049573289990?s=20&t=h6X3lLlJjaBf5SUgX5JEbw), not K3os yet though.

**Comment by ishioni** [comment]
I just switched over, and it works great :)
