### ISSUE TITLE
Cant install on kubernetes v1.22.3

### ISSUE THREAD

**Issue by v0l** [hpe-storage/truenas-csp#24]
Hi, 

One of the `CustomResreouces` is using a deprecated kind.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

```
Error: INSTALLATION FAILED: failed to install CRD crds/hpe-replicated-device-info-crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**Comment by datamattsson** [comment]
Hey @v0l this is a know issue with the Helm chart at the moment. It will be fixed in the next version of the upstream chart. We expect it to drop towards end of January. There might be a beta chart before that. In the meantime, deploy using [the YAML manifest method](https://github.com/hpe-storage/truenas-csp/blob/master/INSTALL.md#install-hpe-csi-driver-for-kubernetes-separately-not-recommended).

**Comment by v0l** [comment]
Thanks @datamattsson I installed directly from the manifest, I have volumes created in TrueNAS but it cant seem to mount them over ISCSI, how does mount these if the portal doesnt have any targets/luns?

**Comment by v0l** [comment]
I switched to `csi-driver` `edge` and that seems to get me a few steps further, i have the targets set on TrueNAS now but mount claims they are not found:

`MountVolume.MountDevice failed for volume "pvc-98909345-bcb3-4300-ba4a-e8f68743da2a" : rpc error: code = Internal desc = Failed to stage volume BLK_hpe-csi_pvc-98909345-bcb3-4300-ba4a-e8f68743da2a, err: rpc error: code = Internal desc = Error creating device for volume BLK_hpe-csi_pvc-98909345-bcb3-4300-ba4a-e8f68743da2a, err: device not found with serial 6589cfc00000098cb404eaaaa4195ac3 or target`

![image](https://user-images.githubusercontent.com/1172179/143139756-37863093-9423-45d5-82db-ae94c1695258.png)

**Comment by v0l** [comment]
system logs show this repeatedly on the k8s node:
```
Nov 23 22:42:56 k8-02 kernel: [39991.966089] sd 7:0:0:0: [sdb] Synchronizing SCSI cache
Nov 23 22:42:56 k8-02 kernel: [39992.045023] scsi 7:0:0:0: alua: Detached
Nov 23 22:42:56 k8-02 kernel: [39992.046190] scsi 7:0:0:0: Direct-Access     TrueNAS  iSCSI Disk       0123 PQ: 0 ANSI: 7
Nov 23 22:42:56 k8-02 kernel: [39992.047022] scsi 7:0:0:0: alua: supports implicit TPGS
Nov 23 22:42:56 k8-02 kernel: [39992.047025] scsi 7:0:0:0: alua: device naa.6589cfc00000098cb404eaaaa4195ac3 port group 1 rel port 4
Nov 23 22:42:56 k8-02 kernel: [39992.047172] sd 7:0:0:0: Attached scsi generic sg2 type 0
Nov 23 22:42:56 k8-02 kernel: [39992.048529] sd 7:0:0:0: [sdb] 1048576000 512-byte logical blocks: (537 GB/500 GiB)
Nov 23 22:42:56 k8-02 kernel: [39992.048530] sd 7:0:0:0: [sdb] 8192-byte physical blocks
Nov 23 22:42:56 k8-02 kernel: [39992.048679] sd 7:0:0:0: [sdb] Write Protect is off
Nov 23 22:42:56 k8-02 kernel: [39992.048681] sd 7:0:0:0: [sdb] Mode Sense: 7f 00 10 08
Nov 23 22:42:56 k8-02 kernel: [39992.048991] sd 7:0:0:0: [sdb] Write cache: enabled, read cache: enabled, supports DPO and FUA
Nov 23 22:42:56 k8-02 kernel: [39992.049455] sd 7:0:0:0: [sdb] Optimal transfer size 1048576 bytes
Nov 23 22:42:56 k8-02 kernel: [39992.065424] sd 7:0:0:0: alua: transition timeout set to 60 seconds
Nov 23 22:42:56 k8-02 kernel: [39992.065426] sd 7:0:0:0: alua: port group 01 state A non-preferred supports TolUSNA
Nov 23 22:42:56 k8-02 kernel: [39992.087376] sd 7:0:0:0: [sdb] Attached SCSI disk
```

**Comment by datamattsson** [comment]
Hey! Thanks for digging in here. What you're seeing here is that the CSI driver can't discover the disk on the host. It only supports multipath devices today, even if you only have a single IP interface. Do you have any idea what the worker node OS is? You might be missing a couple of mandatory stanzas in your /etc/multipath.conf or the multipathing service isn't running properly.

**Comment by v0l** [comment]
I couldnt see a problem with my multipath setup, it seems to mount the disk fine on the OS but its not mounted by kubelet on the container.

`OS: Ubuntu 20.04.03`

**Comment by datamattsson** [comment]
There's an issue with Ubuntu with no fix in sight. The `multipath.conf` you have is provided by the stock package and not the HPE CSI Driver. Remove `/etc/multipath.conf` from the worker nodes and restart the driver: 
```
kubectl rollout restart -n hpe-storage ds/hpe-csi-node
```

**Comment by ishioni** [comment]
@datamattsson any news on that fresh version?

**Comment by datamattsson** [comment]
@ishioni yes! Version 2.1.0 of the HPE CSI Driver will be released next week. I'm hoping to have a fresh cut of the TrueNAS CSP built for this version the following weekend. The multipath issue mentioned in this issue has been addressed too and that will simplify deployment on stock Ubuntu.

**Comment by datamattsson** [comment]
Please give [v2.1.0](https://github.com/hpe-storage/truenas-csp/releases/tag/v2.1.0) a whirl and reopen this bug if problems persist.
