### ISSUE TITLE
Is CHAP auth supported?

### ISSUE THREAD

**Issue by ishioni** [hpe-storage/truenas-csp#26]
Like in the title - will CHAP (or mutual CHAP for that mattter) work?

**Comment by datamattsson** [comment]
CHAP has not been implemented. It should be fairly easy to implement as the CSI driver supports CHAP. Not mutual CHAP though.

**Comment by ishioni** [comment]
I'd be interested. Was using chap with democratic-csi

**Comment by datamattsson** [comment]
@ishioni you can pass in CHAP credentials in the HPE CSI Driver chart. If you do that now, I'm decently sure you'll break volume attachment. At-a-glance, there's an API endpoint to manage CHAP credentials in TrueNAS and it should be pretty straightforward to add. I'm not sure why I left this out to be quite honest.

**Comment by ishioni** [comment]
@datamattsson Any news on this?

**Comment by datamattsson** [comment]
Not yet, I'll see if I can hash this out in the coming weeks.

**Comment by datamattsson** [comment]
This will be looked into after the CHAP rework in the HPE CSI Driver.
