### ISSUE TITLE
Bump the CSI driver for k8s 1.23 compatibility

### ISSUE THREAD

**Issue by ishioni** [hpe-storage/truenas-csp#27]
I see there's a minor HPE CSI driver updates that adds 1.23 compatibility. Can you pull that in?

**Comment by datamattsson** [comment]
Thanks for bringing this up. I'll see if I can have this rebuilt over the weekend.

**Comment by ishioni** [comment]
Any update?

**Comment by datamattsson** [comment]
Yep, I just pushed v2.1.1 in #28 . I found some issues with the chart I got stuck with as the wrong CSP image was being pulled.
