### ISSUE TITLE
Bump csi-driver to 2.2.0

### ISSUE THREAD

**Issue by ishioni** [hpe-storage/truenas-csp#31]
HPE CSI driver released 2.2.0 which brings k8s 1.24 compatibility. Can we have a bump?

**Comment by datamattsson** [comment]
I was actually waiting for Kubernetes 1.25 to drop, which is now out, I'll see if I can get the an environment up this weekend to run the e2e tests. Stay tuned!

**Comment by ishioni** [comment]
@datamattsson any updates on this?

**Comment by datamattsson** [comment]
@ishioni I gave this a whirl over the weekend and truth be told, both my build and lab environment had fallen apart since my last visit. I'm working on standing this back up again.

**Comment by datamattsson** [comment]
I had to improve some of the testing. All good now, v2.2.0 is shipped.

**Comment by ishioni** [comment]
Thanks!
