### ISSUE TITLE
Is v2.4.0 coming?

### ISSUE THREAD

**Issue by msilcher** [hpe-storage/truenas-csp#45]
Hi team,

I have a question, is there a truenas-csp version 2.4.0 planned to be aligned with the newly released hpe-csi v2.4.0? Or can I use trunas-csp v2.3.10 with the latest hpe co-deployments (v2.4.0)?

Thank you!

MS

**Comment by datamattsson** [comment]
Yes, v2.4.0 is in the works. I'll hopefully have it out by next week. If you deploy v2.4.0 of the CSI driver make sure you deploy v2.3.10 of the TrueNAS CSP with the .yaml resource file and not the Helm chart.

**Comment by msilcher** [comment]
Great news, thanks! I'll probably wait until it is fully released but I'll keep in mind about deploying actual version via .yaml instead of Helm.

**Comment by datamattsson** [comment]
Closed in PR #46 
New chart: https://artifacthub.io/packages/helm/truenas-csp/truenas-csp/1.1.5
