### ISSUE TITLE
error downloading truenas-csp 2.4.0 image  

### ISSUE THREAD

**Issue by kingnarmer** [hpe-storage/truenas-csp#48]
I am getting error with truenas-csp controller. 

error :
conGetting ImagePullBackOff (Back-off pulling image "quay.io/datamattsson/truenas-csp:v2.4.0")

**Comment by datamattsson** [comment]
It seems Red Hat has all sorts of issues today. I had RPM issues earlier completely unrelated to this.

![Screenshot_20231114-123450](https://github.com/hpe-storage/truenas-csp/assets/7026024/ac123da7-261d-4823-8d2d-f174def6c7a8)

**Comment by kingnarmer** [comment]
What will be impacted while truenas-csp pod can't get the image ?

**Comment by datamattsson** [comment]
You won't be able to perform any CSI driver related operations, that's for sure. If you're in a pinch you can rebuild the image locally and push to a registry that works.

**Comment by datamattsson** [comment]
You can subscribe to the issue here: https://status.quay.io/

**Comment by kingnarmer** [comment]
issue have been resolved.
