### ISSUE TITLE
Compatibility with FreeNAS-11.3-U5

### ISSUE THREAD

**Issue by maxirus** [hpe-storage/truenas-csp#5]
I know the docs say it requires TrueNAS CORE 12-BETA or higher, but given the age of the repo, is this just because it has **not** been tested on FreeNAS 11.3?

I'm currently using the [FreeNAS Provisioner](https://github.com/nmaupu/freenas-provisioner) and have not moved to the Democratic CSI "fork" as it uses SSH to run raw commands. Some how I stumble upon this before attempting to write my own. Not ready for v12 and am curious if there's some major missing feature in 11.3 that would prevent this from working?

If it's just down to testing and/or potentially incompatible API calls, I'd be happy to test and/or contribute for backwards compatibility.

P.S.: Have you considered packaging this as a Helm Chart and including [HPE CSI Driver](https://artifacthub.io/packages/helm/hpe-storage/hpe-csi-driver) as a dependency?

**Comment by datamattsson** [comment]
Thanks for kicking the tires. To be quite frank I'm not sure why there would be any major incompatibilities with FreeNAS if the APIs are the same. ixSystems have already reached out claiming that TrueNAS SCALE should "just work".

One thing I know you'll run into though if you start exploring FreeNAS 11.3 is that LUNs, once discovered on hosts, will present themselves as something else besides "TrueNAS" "iSCSI Disk" (https://github.com/hpe-storage/common-host-libs/pull/129) when coming off FreeNAS. I started with TrueNAS CORE to be "future proof" and I did not worry too much about adoption of older FreeNAS users. That said, if you compile your own CSI driver image with the FreeNAS disk identities, I'm sure submitting a PR to hpe-storage/csi-driver will be accepted for inclusion in the 1.5.0 release (towards end of May).

Helm chart with dependency is definitely something I'm considering for the 1.5.0 timeframe of the CSI driver as it's being discussed more broadly within the HPE community.

Nevertheless, I'd be happy to work with you on this if it's just a manner of disk identity and such against FreeNAS 11.3.

**Comment by maxirus** [comment]
Thanks for the quick reply. Yep, it does appear that the [vendor](https://github.com/hpe-storage/common-host-libs/pull/129/files#diff-1cc0808850201e4d078d413d8c628a18e1381bbfa83d2dcbc7b56fb387f80049R23) will be presented as `FreeNAS` and thus I assume will **not** be compatible. At first glance it seems like a rather simple fix in upstream.

As for community contributions, it appears I'd have to fork the [common-host-libs](https://github.com/hpe-storage/common-host-libs), update the references [here](https://github.com/hpe-storage/csi-driver/search?q=common-host-libs) to my fork, and then compile the csi-driver?

Are these devices not "overridable" by the plugin?

**Comment by maxirus** [comment]
Forked both the [common-host-libs](https://github.com/maxirus/common-host-libs/commit/77a2ccad586e2c0e687fdb1ca73e77205a6d3de0) and the [CSI Driver](https://github.com/maxirus/csi-driver/commit/c78a286847e16400e9f328e7829153baef593183) with the your mentioned changes. Will try to test tomorrow.

**Comment by datamattsson** [comment]
We discussed this issue internally when I was adding the TrueNAS target and disk identification on how to handle additional backends. Unfortunately, we didn't decide what to do. My hot take is that we should remove it all together as we match up disk serial numbers against what we retrieve from the respective CSP API so it doesn't really matter what the disk/target is called.

Let me know how it goes.

**Comment by maxirus** [comment]
```shell
Sun, 14 Feb 2021 04:42:52 +0000 backend INFO Authentication failed: Unable to authenticate with provided credentials
Sun, 14 Feb 2021 04:43:56 +0000 backend ERROR Backend Request (GET) Exception: Traceback (most recent call last):
File "/app/backend.py", line 225, in get
self.req_backend.raise_for_status()
File "/usr/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://freenas.home.lan/api/v2.0/core/ping
```

I believe API Keys was something new added in v12. Using `root` and `<root_password>` seems to have issues.

**Comment by maxirus** [comment]
Was able to get this project to Authenticate to FreeNAS 11.3-U5 by passing in the username (`root`) and root password via ENV Vars. It seems the Controller does **not** pass the Username as header on subsequent requests so I wasn't able to grab it like you do for password & backend (ie. `req.get_header('x-auth-token')`).

The HPE CSI Stack now runs but mounting the volumes now has issues. I can see the datasets being created as well as the targets in FreeNAS but I'm getting the following event error on Pod startup:
```shell
MountVolume.MountDevice failed for volume "pvc-a7351b99-9b7b-429d-9748-568c984ed1a7" : rpc error: code = Internal desc = Failed to stage volume tank_k8s-iscsi_pvc-a7351b99-9b7b-429d-9748-568c984ed1a7, err: rpc error: code = Internal desc = Error creating device for volume tank_k8s-iscsi_pvc-a7351b99-9b7b-429d-9748-568c984ed1a7, err: device not found with serial 6589cfc000000e29cff27d6ad9aedb8f or target
```
Target in FreeNAS:
![image](https://user-images.githubusercontent.com/1676208/107991070-d6430180-6fa3-11eb-87df-22e6cbe6457c.png)

Will try to debug a little more tonight but if you have any pointers, that'd be great.

**Comment by datamattsson** [comment]
Hey, cool you got this far. The error the CSI driver is emitting is usually related to the device not being created properly on the host. Given you require the FreeNAS disk device changes I wonder if devices show up with `multipath -ll`? Given you're using a Debian derive as compute node, I've seen that you have to set `find_multipaths no` in multipath.conf if you only have one subnet in those situations.

The [CSI driver logs](https://scod.hpedev.io/csi_driver/diagnostics.html#logging) will tell you more and you can also crank up the log level for further troubleshooting.

**Comment by maxirus** [comment]
Good call. Creating dir/file `/etc/multipath/conf.d/multipath.conf` and adding:
```
defaults {
    find_multipaths "no"
}
```
seems to have done the trick. I can now see:
```shell
# multipath -ll
mpathb (36589cfc00000000a00539376ce3dde81) dm-0 FreeNAS,iSCSI Disk
size=32G features='0' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  `- 6:0:0:0 sdb 8:16 active ready running
```
and the Pod has come up.

Is there a way to disable multipath'ing in the Driver? I would assume users would run into this same issue using TrueNAS 12 as well if they weren't running iSCSI in multipath mode. In which case, most home/lab users would need to disable this.

As for my features/fixes, I'll open PRs to the various repos that need to be updated and contribute the necessary Docs.

Thanks.
