### ISSUE TITLE
Dynamically have provisioning parameters for pvc

### ISSUE THREAD

**Issue by kingnarmer** [hpe-storage/truenas-csp#54]
Make "extra-create-metadata" parameters available at the time pvc is created . Ex: Be able to dynamically add pvc namespace to description section. 

something like 

description: "PVC created  on ${paramters.namespace}"

**Comment by datamattsson** [comment]
I'm getting a bit of Deja Vu here as I think I've mean to implement this somewhere. Either in the upstream CSI driver or the CSP. They way this would work is that you'll have access to {pvc} and {namespace} for the description field.

**Comment by kingnarmer** [comment]
@datamattsson  Do you mean it should work now ? Like if I set the description on the Storage class to description: "PVC created on {namespace}" ?

**Comment by datamattsson** [comment]
I could not find any traces of it, but I'll add it to the next release.

**Comment by datamattsson** [comment]
Updated docs.
