### ISSUE TITLE
Error API authenticate to TrueNAS SCALE

### ISSUE THREAD

**Issue by muhammadnourmanhadi** [hpe-storage/truenas-csp#60]
Hi, 
I got error in TrueNAS SCALE Dragonfish-24.04.2 and RKE2 with Kubernetes Version: v1.28.11 
follow completely guide, but authenticate not allowed, i check in truenas Audit, every Event Credentials: API Key get Error: Null

TrueNAS Event Data like this:
Credentials:
  Credentials: API_KEY
  Credentials Data:
    Api Key: xxxx
Error: Null

then I check log hpe-csi-controller got:
2024-08-11T00:02:08.549368797+07:00 I0810 17:02:08.549323       1 controller.go:848] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = Failed to create volume pvc-c54b671c-1567-47e1-bcf8-b5816d54a146, Request failed with status code 500 and errors Error code (Bad Request) and message (TrueNAS API returned: {
2024-08-11T00:02:08.549373663+07:00  "path": [
2024-08-11T00:02:08.549376847+07:00   {
2024-08-11T00:02:08.549382731+07:00    "message": "null not allowed",
2024-08-11T00:02:08.549386074+07:00    "errno": 22
2024-08-11T00:02:08.549389149+07:00   }
2024-08-11T00:02:08.549392215+07:00  ]
2024-08-11T00:02:08.549395239+07:00 })

I dont now to resolve this issue, can i get help? thank you

**Comment by datamattsson** [comment]
Strange. 24.04 has not been tested yet AFAIK, but I would be surprised if they had made any drastic changes to the API. 

What does your `StorageClass` and `Secret` look like?

**Comment by muhammadnourmanhadi** [comment]
This is my StorageClass:
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: hpe-storageclass
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: truenas-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: hpe-storage
  csi.storage.k8s.io/controller-publish-secret-name: truenas-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-publish-secret-name: truenas-secret
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-storage
  csi.storage.k8s.io/node-stage-secret-name: truenas-secret
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-storage
  csi.storage.k8s.io/provisioner-secret-name: truenas-secret
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-storage
  csi.storage.k8s.io/fstype: xfs
  allowOverrides: sparse,compression,deduplication,volblocksize,sync,description
  root: nas/kubernetes
reclaimPolicy: Delete
allowVolumeExpansion: true

---

and my secret:
---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: hpe-storage
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: hpe-csi
  password: "my API key"
  backend: 192.168.88.2

**Comment by datamattsson** [comment]
Can you fix the indentation on these so I can verify they're correct?

**Comment by muhammadnourmanhadi** [comment]
done

**Comment by datamattsson** [comment]
That looks correct. TrueNAS must've changed something in the 24.04 API, I will have a look. I'm busy the next few days but I'll have this resolved.

**Comment by datamattsson** [comment]
Running some more tests on 24.04.2 and I don't think it's safe to use at this point with the CSI driver. I've sort of hit the same issue you're reported.

**Comment by datamattsson** [comment]
I've worked on this the past week and I have a working solution. I'm hoping to have this wrapped up next week.
