### ISSUE TITLE
Trunas-CSP 2.5.0

### ISSUE THREAD

**Issue by msilcher** [hpe-storage/truenas-csp#61]
Hi Michael,

Question: is there a version 2.5.0 coming for Truenas-CSP to align to the HPE CSI 2.5.0?
Is it possible to use TruenasCSP 2.4.2 with HPE CSI 2.5.0?

Thanks!!

MS

**Comment by datamattsson** [comment]
> Is it possible to use TruenasCSP 2.4.2 with HPE CSI 2.5.0?

There's been no changes to the CSP spec so you can deploy TrueNAS CSP 2.4.2 (with the YAML manifest) and the bare HPE CSI Driver Helm chart.

However, there are many improvements made in CHAP and `volumeMode: Block` (RWX in particular) that needs to be addressed in the TrueNAS CSP. It will take a while to implement unfortunately but I'm setting up an environment for this as we speak.

**Comment by datamattsson** [comment]
> There's been no changes to the CSP spec so you can deploy TrueNAS CSP 2.4.2 (with the YAML manifest) and the bare HPE CSI Driver Helm chart.

I'll take that back. I tried this and there are issues I can't quite isolate yet so please sit tight.

**Comment by msilcher** [comment]
> > There's been no changes to the CSP spec so you can deploy TrueNAS CSP 2.4.2 (with the YAML manifest) and the bare HPE CSI Driver Helm chart.
> 
> I'll take that back. I tried this and there are issues I can't quite isolate yet so please sit tight.

Ok, thank for your feedback! I'll wait for further instructions :)

**Comment by datamattsson** [comment]
Just a short update that I've made some strides in this department and have a stable build. There's still a lot to do but I'll hopefully get more time this coming looooong weekend to wrap things up.
